[theme]
base = "dark"
primaryColor = "#8b7CFF"
backgroundColor = "#0B0E14"
secondaryBackgroundColor = "#131722"
textColor = "#E7E9F1"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
